//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace SiegenerXmlNarrator.Model
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class game
  {

    private variable[] varsField;

    private sec[] secField;

    /// <remarks/>
    [XmlArrayItem("var", IsNullable = false)]
    public variable[] vars
    {
      get { return this.varsField; }
      set { this.varsField = value; }
    }

    /// <remarks/>
    [XmlElement("sec")]
    public sec[] sec
    {
      get { return this.secField; }
      set { this.secField = value; }
    }
  }
}